preventing AttributeError caused by tensor.shape[axis].value in tf 2.0
in tf 2.0 `tensor.shape[axis].value`  raises "AttributeError: 'int' object has no attribute 'value'" if not executed eagerly. 
Demonstration:
https://colab.research.google.com/drive/1TTtNwEF4TjWQoXdvjpWky-dnXN1zFu13#scrollTo=V5vOv0Qnl1Tk
It's replaced in `_check_tensors` function by `_get_dim(tensor,axis)`  as proposed by @julienvalentin in https://github.com/tensorflow/graphics/issues/15#issuecomment-533034402_